parsers:
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
- crowdsecurity/sshd-logs
scenarios:
- "./scenarios/crowdsecurity/ssh-generic-test.yaml"
postoverflows:
- ""
log_file: ssh-generic-test.log
log_type: syslog
labels: {}
ignore_parsers: false
override_statics: []
