parsers:
- crowdsecurity/syslog-logs
- crowdsecurity/nginx-logs
- crowdsecurity/http-logs
- crowdsecurity/dateparse-enrich
scenarios:
- "./scenarios/crowdsecurity/http-generic-test.yaml"
postoverflows:
- ""
log_file: http-generic-test.log
log_type: nginx
ignore_parsers: true
override_statics: []
