parsers:
  - ./parsers/s00-raw/crowdsecurity/syslog-logs.yaml
  - ./parsers/s01-parse/PintjesB/technitium-logs.yaml
scenarios:
    #- "./scenarios/PintjesB/unifi-firewall-hits.yaml"
postoverflows:
    - ""
log_file: technitium.log
log_type: technitium
