name: Update Blockers Meta

on:
  push:
    paths:
      - 'blockers/list.json'
      - '*.go'
      - '.github/workflows/update-blockers.yml'
  pull_request:
    branches:
      - master

jobs:
  check_blockers:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: 1.19
    - uses: actions/checkout@v4
    - name: Create local changes
      run: |
        go build
        ./main -target blockers
    - name: set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pipenv'
    - name: install dependencies
      run: |
        python -m pip install --upgrade pipenv wheel
        pipenv install --deploy
    - name: run mkblockers
      run: |
        jq --sort-keys --indent 2 < blockers.json >blockers-sorted.json
        pipenv run ./mkblockers
        if ! (cmp -s blockers-sorted.json blockers-new.json); then
            echo "Error: output from mkblockers differs from legacy blockers builder."
            diff -u blockers-sorted.json blockers-new.json
            exit 1
        fi
